namespace AiService.Application.Services;

/// <summary>
/// Contract for calling the Google Gemini AI API.
/// Implemented by <see cref="AiService.Infrastructure.GeminiService"/>.
///
/// WHY AN INTERFACE:
///   The controller depends on this interface, not the concrete class.
///   This means:
///   1. You can swap Gemini for OpenAI or any other AI without touching the controller.
///   2. Unit tests can mock this interface without making real API calls.
/// </summary>
public interface IGeminiService
{
    /// <summary>
    /// Sends a payload to the Gemini API and returns the generated text response.
    /// The payload is serialized to JSON and POSTed to the Gemini REST endpoint.
    /// </summary>
    /// <param name="payload">
    /// An anonymous object containing:
    /// - system_instruction: the AI's persona and rules
    /// - contents: the conversation history + current message
    /// - generationConfig: temperature, maxOutputTokens
    /// </param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>The raw text generated by Gemini.</returns>
    /// <exception cref="Exception">Thrown when Gemini returns a non-success HTTP status.</exception>
    Task<string> GenerateAsync(object payload, CancellationToken ct = default);
    /// <summary>
    /// Returns true if a valid Gemini API key is configured.
    /// Returns false if the key is missing or still set to the placeholder value.
    /// Used by the controller to return 503 instead of crashing when key is not set.
    /// </summary>
    bool IsConfigured { get; }
}